### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by d4rkc0nd0r**
Added ProjectQ.

### CODE REVIEW

**Comment by kottmanj** [comment]
Hi, thanks for the PR.
Currently it only contains adding ProjectQ to the Tequila readme but not adding actual support for ProjectQ to tequila. In the readme we list the quantum backends that are actually supported in tequila (i.e. where you can do things like: tq.simulate(tq_obective, backend="qulacs"). Are you intending to add support for ProjectQ (which would be great!)?

**Comment by d4rkc0nd0r** [comment]
Hi @kottmanj,
Ya it would be a great pleasure to add support to the ProjectQ.

**Comment by d4rkc0nd0r** [comment]
Sure I'll do that.

**Comment by kottmanj** [comment]
Awesome :-)

**Comment by kottmanj** [comment]
Closing this PR for now

**Pull request closed without merging**
