### PR TITLE
Added DIIS acceleration to gradient descent algorithms

### PR DESCRIPTION
**Pull request by clavigne**
This is a prototype for DIIS acceleration of GD algorithm. DIIS basically makes gradient descent actually feasible, in that it accelerates it significantly for the last few sig figs once close to the solution.

Currently missing:
- A way to detect that the GD algorithm is not compatible (I think that's only the case for nesterov)
- A way to start DIIS when error is below a given margin (DIIS only works when relatively close to the solution)

### CODE REVIEW

**Comment by clavigne** [comment]
It's alive!

Great convergence awaits.

**Comment by kottmanj** [comment]
Coolio!
Could you copy an example into the optimizer_tutorial notebook? Otherwise I'm afraid it will get lost.

**Comment by clavigne** [comment]
Oops, I made a small error in the implementation. will fix, don't merge just yet.

**Comment by kottmanj** [comment]
Let me know when it's ready

**Comment by clavigne** [comment]
It's ready for devel at least.

We need better stopping criterions for GD optimizer (and thus for DIIS), and I should probably spin off a "pure" DIIS optimizer instead of mixing it with GD, but I think that can wait a bit.

**Pull request merged**
